### ISSUE TITLE
Doesn't that tool already exists?

### ISSUE THREAD

**Issue by jbouhier** [TheWallStreetAnalytics/wallstreetanalytics#36] opened 2021-02-20 03:23 UTC
Just saw https://www.memebergterminal.com on r/pennystocks

**Comment by paralllax** [comment] 2021-02-20 04:47
As far as I am aware, that tool is not open source. It has a considerably smaller development team as well. There are lots of similar tools such as https://unbiastock.com/twitter.php#

However, none align with the current goals nor match the level support this project _currently_ has.

**Comment by itsclaireh** [comment] 2021-02-20 04:49
I just posted an announcement on the discord that cover these types of
concerns in the next steps.

In the coming days, we will find Subject Matter Experts from our community
on discord to lead each technical/specialty area. It will be these people's
responsibility to look into existing projects, determine if that's
something we need in our goal together, and reach out to those owners to
include them in our project. There is no need to reinvent the wheel.

**Comment by vito-c** [comment] 2021-02-20 05:56
@itsclaireh did you start a discord for this repo or did you post it in the `wsb` one? could you send me an invite to the  discord? Thanks.

**Comment by paralllax** [comment] 2021-02-20 06:49
@vito-c See here to join:

https://github.com/TheWallStreetAnalytics/wallstreetanalytics/issues/2#issuecomment-781749248

**Comment by zoox101** [comment] 2021-02-20 08:16
Duplicate of #34 continuing the discussion on that thread

**Closed as completed by zoox101** 2021-02-20 08:16 UTC
