### ISSUE TITLE
License Licenses Licenses

### ISSUE THREAD

**Issue by vito-c** [TheWallStreetAnalytics/wallstreetanalytics#9] opened 2021-02-19 03:12 UTC
I think a really important part of this project is going to be picking your license. You are going to want to pick something that fits tightly with your goals. I am thinking your main purposes it to  create a set of tools to help the everyday investor get a level playing field with the HF. So you want to make sure that the HF are not able to steal all of your hard earned work.

WE can protect the code that we write by the license that we pick. I do not know all of the specifics here but it's definitely worth sometime thinking about what exactly we want to achieve. Do we want to create an open source project that ANYONE (including HF) is free to use and incorporate into their tech stacks. Or do we want to create a dual license software where companies are allowed to purchase the right to use our software and everyday individuals are allowed to use our software freely.

Here are some links on licenses:
https://choosealicense.com/licenses/
https://opensource.stackexchange.com/questions/9805/can-i-license-my-project-with-an-open-source-license-but-disallow-commercial-use

I am not suggesting a choice but rather trying to start a discussion. I also think it would be  best to figure out which license(s) to pick before writing too much code.

**Comment by DrewMcArthur** [comment] 2021-02-19 03:16
duplicate of #4 :) 

would be cool to put discussion there so that it’s all in one place! (unless you think here is a better place to start that discussion, otherwise i’d say copy your comment over there)

**Comment by DrewMcArthur** [comment] 2021-02-19 03:18
woo!! first issue closed, look at us go 🤩

**Closed as completed** 2021-02-19 03:17 UTC
